language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - nightly
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer selfupdate

install:
  - composer install --no-interaction

script:
  - phpunit --bootstrap vendor/autoload.php tests/
